server {
    listen 8093;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /video {
        proxy_pass http://driver-video:8091/;
        proxy_buffering off;
    }

    location /ws/hid/unifying {
        proxy_pass http://driver-hid-unifying:8095/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /ws/hid/esp32 {
        proxy_pass http://driver-hid-esp32:8096/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
